name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.1
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bip39:
    git:
      url: https://github.com/RomitRadical/bip39
      ref: master
  bip32:
    git:
      url: https://github.com/jbdtky/bip32-dart
      ref: master
  pointycastle:
    git:
      url: https://github.com/jbdtky/pc-dart.git
      ref: master
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.1.5
  bech32: 0.1.2

dev_dependencies:
  test: ^1.0.0
